@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "ltseed.chatinmc.ChatInMC#onEnable()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": false, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": true,
    "showMethodParametersNames": true,
    "showMethodReturnType": true,
    "showPackageLevels": 5,
    "showCallOrder": true,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": true
  },
  "rootClass": "ltseed.chatinmc.ChatInMC",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1438026963 { 
   	label=chatinmc
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1737928423 { 
   	label=ChatInMC
	labeljust=l
	fillcolor=white
	style=filled
   
   ChatInMC1813016792XXXonEnable0[
	label="+ onEnable()"
	style=filled
	fillcolor=white
	tooltip="ChatInMC

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_1966903370 { 
   	label=Utils
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1645467689 { 
   	label=CmdTest
	labeljust=l
	fillcolor=white
	style=filled
   
   CmdTest685466037XXXtest0[
	label="+ test()"
	style=filled
	fillcolor=white
	tooltip="CmdTest

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1857076684 { 
   	label=Request
	labeljust=l
	fillcolor=white
	style=filled
   
   Request685466037XXXget852237021[
	label="+ get(url: String, header: Map<String, String>): JSONObject"
	style=filled
	fillcolor=white
	tooltip="Request

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_597279248 { 
   	label=FileProcess
	labeljust=l
	fillcolor=white
	style=filled
   
   FileProcess685466037XXXcheckFolders1901307053[
	label="+ checkFolders(tp: Plugin)"
	style=filled
	fillcolor=white
	tooltip="FileProcess

null"
	fontcolor=darkgreen
];

FileProcess685466037XXXreadChatters0[
	label="+ readChatters(): Map<UUID, Chatter>"
	style=filled
	fillcolor=white
	tooltip="FileProcess

null"
	fontcolor=darkgreen
];

FileProcess685466037XXXreadModels0[
	label="+ readModels(): List<String>"
	style=filled
	fillcolor=white
	tooltip="FileProcess

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_83305371 { 
   	label=Config
	labeljust=l
	fillcolor=white
	style=filled
   
   Config685466037XXXreadConfig0[
	label="+ readConfig()"
	style=filled
	fillcolor=white
	tooltip="Config

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_470348790 { 
   	label=PlayerInteraction
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1173882659 { 
   	label=GUI
	labeljust=l
	fillcolor="#c4c4c4"
	style=filled
   
   subgraph cluster_1014417235 { 
   	label=SimpleGUI
	labeljust=l
	fillcolor=white
	style=filled
   
   SimpleGUI689662904XXXenableView0[
	label="+ enableView()"
	style=filled
	fillcolor=white
	tooltip="SimpleGUI

null"
	fontcolor=darkgreen
];
} 
} 
} 

subgraph cluster_890550284 { 
   	label=Talker
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1136230640 { 
   	label=DialogFlow
	labeljust=l
	fillcolor="#c4c4c4"
	style=filled
   
   subgraph cluster_1578896762 { 
   	label=CloudSDKInstaller
	labeljust=l
	fillcolor=white
	style=filled
   
   CloudSDKInstaller1678276613XXXinstall0[
	label="+ install()"
	style=filled
	fillcolor=white
	tooltip="CloudSDKInstaller

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_2144035337 { 
   	label=DialogFlowInstaller
	labeljust=l
	fillcolor=white
	style=filled
   
   DialogFlowInstaller1678276613XXXinstall0[
	label="+ install()"
	style=filled
	fillcolor=white
	tooltip="DialogFlowInstaller

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_900357657 { 
   	label=ChatGPT
	labeljust=l
	fillcolor="#c4c4c4"
	style=filled
   
   subgraph cluster_266402097 { 
   	label=ChatGPTModelUtils
	labeljust=l
	fillcolor=white
	style=filled
   
   ChatGPTModelUtils1485060316XXXgetAvailableModels1808118735[
	label="+ getAvailableModels(key: String): List<String>"
	style=filled
	fillcolor=white
	tooltip="ChatGPTModelUtils

null"
	fontcolor=darkgreen
];
} 
} 
} 
} 

'edges    
ChatGPTModelUtils1485060316XXXgetAvailableModels1808118735 -> Request685466037XXXget852237021[label=3];
ChatGPTModelUtils1485060316XXXgetAvailableModels1808118735 -> Request685466037XXXget852237021[label=5];
ChatInMC1813016792XXXonEnable0 -> ChatGPTModelUtils1485060316XXXgetAvailableModels1808118735[label=14];
ChatInMC1813016792XXXonEnable0 -> CloudSDKInstaller1678276613XXXinstall0[label=7];
ChatInMC1813016792XXXonEnable0 -> CmdTest685466037XXXtest0[label=5];
ChatInMC1813016792XXXonEnable0 -> Config685466037XXXreadConfig0[label=1];
ChatInMC1813016792XXXonEnable0 -> DialogFlowInstaller1678276613XXXinstall0[label=9];
ChatInMC1813016792XXXonEnable0 -> FileProcess685466037XXXcheckFolders1901307053[label=11];
ChatInMC1813016792XXXonEnable0 -> FileProcess685466037XXXreadChatters0[label=15];
ChatInMC1813016792XXXonEnable0 -> FileProcess685466037XXXreadModels0[label=12];
ChatInMC1813016792XXXonEnable0 -> SimpleGUI689662904XXXenableView0[label=4];
    
}
@enduml