@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "ltseed.chatinmc.Commands#onCommand(CommandSender,Command,String,String[])",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": false, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": true,
    "showMethodParametersNames": true,
    "showMethodReturnType": true,
    "showPackageLevels": 5,
    "showCallOrder": true,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": true
  },
  "rootClass": "ltseed.chatinmc.Commands",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1438026963 { 
   	label=chatinmc
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_470348790 { 
   	label=PlayerInteraction
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1173882659 { 
   	label=GUI
	labeljust=l
	fillcolor="#c4c4c4"
	style=filled
   
   subgraph cluster_1014417235 { 
   	label=SimpleGUI
	labeljust=l
	fillcolor=white
	style=filled
   
   SimpleGUI689662904XXXaddButton2001146706[
	label="+ addButton(button: Button)"
	style=filled
	fillcolor=white
	tooltip="SimpleGUI

null"
	fontcolor=darkgreen
];

SimpleGUI689662904XXXenableView0[
	label="+ enableView()"
	style=filled
	fillcolor=white
	tooltip="SimpleGUI

null"
	fontcolor=darkgreen
];

SimpleGUI689662904XXXopen1901885695[
	label="+ open(player: Player)"
	style=filled
	fillcolor=white
	tooltip="SimpleGUI

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_108376516 { 
   	label=PaginatedGUI
	labeljust=l
	fillcolor=white
	style=filled
   
   PaginatedGUI689662904XXXopen2119573606[
	label="+ open(player: Player, page: int)"
	style=filled
	fillcolor=white
	tooltip="PaginatedGUI

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_659227024 { 
   	label=FinalGUI
	labeljust=l
	fillcolor="#bababa"
	style=filled
   
   subgraph cluster_1478540535 { 
   	label=ChatterCreateGUI
	labeljust=l
	fillcolor=white
	style=filled
   
   ChatterCreateGUI1411321477XXXgetInstance1901885695[
	label="+ getInstance(player: Player): ChatterCreateGUI"
	style=filled
	fillcolor=white
	tooltip="ChatterCreateGUI

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1744339456 { 
   	label=ChatterManageGUI
	labeljust=l
	fillcolor=white
	style=filled
   
   ChatterManageGUI1411321477XXXgetInstance287481900[
	label="+ getInstance(player: Player, chatter: Chatter): ChatterManageGUI"
	style=filled
	fillcolor=white
	tooltip="ChatterManageGUI

null"
	fontcolor=darkgreen
];
} 
} 
} 
} 

subgraph cluster_517430958 { 
   	label=Commands
	labeljust=l
	fillcolor=white
	style=filled
   
   Commands1813016792XXXonCommand253956253[
	label="+ onCommand(sender: CommandSender, command: Command, label: String, args: String[]): boolean"
	style=filled
	fillcolor=white
	tooltip="Commands

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_890550284 { 
   	label=Talker
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1485016390 { 
   	label=Chatter
	labeljust=l
	fillcolor=white
	style=filled
   
   Chatter179301375XXXdescribe0[
	label="+ describe(): Map<String, Object>"
	style=filled
	fillcolor=white
	tooltip="Chatter

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
Commands1813016792XXXonCommand253956253 -> Chatter179301375XXXdescribe0[label=14];
Commands1813016792XXXonCommand253956253 -> ChatterCreateGUI1411321477XXXgetInstance1901885695[label=5];
Commands1813016792XXXonCommand253956253 -> ChatterManageGUI1411321477XXXgetInstance287481900[label=20];
Commands1813016792XXXonCommand253956253 -> PaginatedGUI689662904XXXopen2119573606[label=21];
Commands1813016792XXXonCommand253956253 -> SimpleGUI689662904XXXopen1901885695[label=19];
Commands1813016792XXXonCommand253956253 -> SimpleGUI689662904XXXopen1901885695[label=4];
PaginatedGUI689662904XXXopen2119573606 -> PaginatedGUI689662904XXXopen2119573606[label=11];
PaginatedGUI689662904XXXopen2119573606 -> PaginatedGUI689662904XXXopen2119573606[label=8];
PaginatedGUI689662904XXXopen2119573606 -> SimpleGUI689662904XXXaddButton2001146706[label=5];
PaginatedGUI689662904XXXopen2119573606 -> SimpleGUI689662904XXXaddButton2001146706[label=6];
PaginatedGUI689662904XXXopen2119573606 -> SimpleGUI689662904XXXaddButton2001146706[label=9];
PaginatedGUI689662904XXXopen2119573606 -> SimpleGUI689662904XXXopen1901885695[label=12];
SimpleGUI689662904XXXopen1901885695 -> SimpleGUI689662904XXXenableView0[label=0];
    
}
@enduml