name: ChatInMC
version: '${project.version}'
main: ltseed.chatinmc.ChatInMC
api-version: 1.19
description: chat in mc!
load: POSTWORLD

commands:
  cim:
    description: 启用 ChatInMC 插件
    usage: /cim help

permissions:
  chatinmc.admin:
    description: 允许管理员使用 ChatInMC 插件
    default: op
