@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": false,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": false,
    "cutConstructors": false
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": false, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "ltseed.chatinmc.PlayerInteraction.GUI.Button",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1438026963 { 
   	label=chatinmc
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_470348790 { 
   	label=PlayerInteraction
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Button689662904[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Button</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   displayName: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   lore: List&lt;String&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   material: Material [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   skullOwner: UUID [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   texture: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   x: short [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   y: short [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ Button(x: short, y: short, material: Material, displayName: String, lore: List&lt;String&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >+ Button(slot: int, material: Material, displayName: String, lore: List&lt;String&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >+ Button(slot: int, is: ItemStack)</TD></TR>
<TR><TD ALIGN="LEFT" >+ call(player: Player)</TD></TR>
<TR><TD ALIGN="LEFT" >- createSkullItemStack(owner: UUID, displayName: String, lore: List&lt;String&gt;, texture: String): ItemStack</TD></TR>
<TR><TD ALIGN="LEFT" >+ getSlot(): int</TD></TR>
<TR><TD ALIGN="LEFT" >- readTexture(imageFile: File): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ setupButton(inventory: Inventory)</TD></TR>
<TR><TD ALIGN="LEFT" >+ toItemStack(): ItemStack</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ChatterCreateGUI1411321477[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ChatterCreateGUI</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   best_of: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   choose_entity: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   core: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   core_name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   description: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   dur: long [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   frequency_penalty: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   logprobs: Integer [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   material: Material [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   max_tokens: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   n: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   presence_penalty: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   projectId: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   suffix: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   talkDistance: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   temperature: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   top_p: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- ChatterCreateGUI(player: Player)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getInstance(player: Player): ChatterCreateGUI</TD></TR>
<TR><TD ALIGN="LEFT" >- init(player: Player)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ChatterManageGUI1411321477[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ChatterManageGUI</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   best_of: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   choose_entity: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   core_name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   description: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   dur: long [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   frequency_penalty: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   logprobs: Integer [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   material: Material [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   max_tokens: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   n: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   presence_penalty: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   projectId: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   suffix: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   talkDistance: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   temperature: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   top_p: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- ChatterManageGUI(player: Player, chatter: Chatter)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getInstance(player: Player, chatter: Chatter): ChatterManageGUI</TD></TR>
<TR><TD ALIGN="LEFT" >- init(player: Player)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

PaginatedGUI689662904[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PaginatedGUI</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   allButtons: List&lt;Button&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nextPageItem: ItemStack [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   pages: Map&lt;Integer, List&lt;Button&gt;&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   prevPageItem: ItemStack [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   title: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   totalPages: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ PaginatedGUI(title: String, allButtons: List&lt;Button&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >+ open(player: Player, page: int)</TD></TR>
<TR><TD ALIGN="LEFT" >- setupPages()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SimpleGUI689662904[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SimpleGUI</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   buttons: Map&lt;Integer, Button&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   inventory: Inventory [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># SimpleGUI(inventoryName: String, buttons: Map&lt;Integer, Button&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >+ addButton(button: Button)</TD></TR>
<TR><TD ALIGN="LEFT" >+ enableView()</TD></TR>
<TR><TD ALIGN="LEFT" >+ onInventoryClick(event: InventoryClickEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ open(player: Player)</TD></TR>
<TR><TD ALIGN="LEFT" ># setupButtons(buttons: Collection&lt;Button&gt;)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
PaginatedGUI689662904 -> Button689662904[label="allButtons
[0..*]"];
PaginatedGUI689662904 -> Button689662904[label="pages
[0..*]"];
SimpleGUI689662904 -> Button689662904[label="buttons
[0..*]"];
SimpleGUI689662904 -> ChatterCreateGUI1411321477[arrowhead=none, arrowtail=empty, dir=both];
SimpleGUI689662904 -> ChatterManageGUI1411321477[arrowhead=none, arrowtail=empty, dir=both];
    
}
@enduml